version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  web:
    build: .
    restart: always
    env_file: .env
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: