version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - media:/app/media
      - static:/app/static
    depends_on:
      - db

volumes:
  postgres_data:
  static:
  media: