# Generated by Django 4.2 on 2025-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_text', models.TextField(help_text='Введите текст миссии организации', verbose_name='Миссия организации')),
                ('ambitions_text', models.TextField(help_text='Введите текст об амбициях организации', verbose_name='Амбиции')),
                ('five_year_goal', models.TextField(help_text='Введите цели организации на 5 лет', verbose_name='Цель на 5 лет')),
                ('tasks_text', models.TextField(help_text='Введите основные задачи организации', verbose_name='Задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'миссия',
                'verbose_name_plural': 'миссия',
            },
        ),
    ]
