# Generated by Django 4.2 on 2025-05-06 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видео о нас',
                'verbose_name_plural': 'Видео о нас',
            },
        ),
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='gratitudes/', verbose_name='Файл благодарности')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше значение, тем первее в списке', verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Видимость в ленте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Благодарность',
                'verbose_name_plural': 'Благодарности',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Название партнера*')),
                ('logo', models.ImageField(help_text='Обязательное поле', upload_to='partners/logos/', verbose_name='Логотип партнера*')),
                ('description', models.TextField(help_text='Обязательное поле', verbose_name='Описание*')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('author_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя автора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='supervisors/', verbose_name='Фото')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.SlugField(choices=[('aba-therapy', 'ABA-терапия'), ('adaptive-physical-culture', 'Адаптивная физкультура'), ('creative-workshops', 'Творческие мастерские'), ('resource-classes', 'Ресурсные классы'), ('children-leisure', 'Досуг для детей')], max_length=255, verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'Супервизор',
                'verbose_name_plural': 'Супервизоры',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='TargetedFundraising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('status', models.CharField(choices=[('active', 'Актуальный сбор'), ('completed', 'Завершенный сбор')], default='active', max_length=10, verbose_name='Статус сбора')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше значение, тем первее в списке', verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Адресный сбор',
                'verbose_name_plural': 'Адресные сборы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundraisingTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(verbose_name='Текстовый блок')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Позиция блока (1-3)')),
                ('fundraising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='content.targetedfundraising', verbose_name='Адресный сбор')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FundraisingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fundraisings/', verbose_name='Фотография')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Позиция фотографии (1-3)')),
                ('fundraising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.targetedfundraising', verbose_name='Адресный сбор')),
            ],
            options={
                'verbose_name': 'Фотография сбора',
                'verbose_name_plural': 'Фотографии сборов',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='fundraisingtextblock',
            constraint=models.UniqueConstraint(fields=('fundraising', 'position'), name='unique_text_position'),
        ),
        migrations.AddConstraint(
            model_name='fundraisingphoto',
            constraint=models.UniqueConstraint(fields=('fundraising', 'position'), name='unique_photo_position'),
        ),
    ]
