# Generated by Django 4.2 on 2025-04-07 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок*')),
                ('short_description', models.TextField(verbose_name='Краткое описание*')),
                ('status', models.CharField(choices=[('active', 'Актуальный сбор'), ('completed', 'Завершенный сбор')], default='active', max_length=10, verbose_name='Статус сбора*')),
                ('collection_link', models.URLField(verbose_name='Ссылка на сбор*')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Адресный сбор',
                'verbose_name_plural': 'Адресные сборы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(verbose_name='Текстовый блок')),
                ('position', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Позиция блока (1-3)')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='content.addresscollection')),
            ],
            options={
                'verbose_name': 'Текстовый блок',
                'verbose_name_plural': 'Текстовые блоки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/', verbose_name='Фото')),
                ('position', models.PositiveIntegerField(default=0, help_text='Позиция фото (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.addresscollection')),
            ],
            options={
                'verbose_name': 'Фото сбора',
                'verbose_name_plural': 'Фото сборов',
                'ordering': ['position'],
            },
        ),
    ]
