# Generated by Django 4.2 on 2025-05-28 15:51

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='achieved_results',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Достигнутые результаты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_rassvet',
            field=models.BooleanField(default=False, verbose_name='Проект НКО Рассвет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_financing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='content.partner', verbose_name='Источник софинансирования - Партнёр'),
        ),
    ]
