# Generated by Django 4.2 on 2025-06-03 10:43

import content.models.report
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_partner_options_alter_partner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название раздела')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Позиция на странице')),
            ],
            options={
                'verbose_name': 'Раздел отчетов',
                'verbose_name_plural': 'Разделы отчетов',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название отчета')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, help_text='Публикации сортируются от новых к старым', verbose_name='Дата публикации')),
                ('file', models.FileField(upload_to=content.models.report.upload_file, verbose_name='Файл отчета')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-pub_date'],
            },
        ),
    ]
