# Generated by Django 4.2 on 2025-06-11 22:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_employee_options_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Основной текст'),
        ),
    ]
