# Generated by Django 4.2 on 2025-06-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_news_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='download_icon',
            field=models.BooleanField(default=True, verbose_name='Иконка скачивания'),
        ),
    ]
