# Generated by Django 4.2 on 2025-06-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_report_download_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order'], 'verbose_name': 'Раздел отчетов', 'verbose_name_plural': 'Разделы отчетов'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('order',), 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='position',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
