# Generated by Django 4.2 on 2025-06-14 21:15

import content.models.employees
import content.models.news
import content.models.report
import content.models.targeted_fundraisings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_chapter_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='gratitude',
            options={'ordering': ['order'], 'verbose_name': 'Благодарность', 'verbose_name_plural': 'Благодарности'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Миссия', 'verbose_name_plural': 'Миссии'},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_rassvet',
        ),
        migrations.AlterField(
            model_name='aboutusvideo',
            name='title',
            field=models.CharField(blank=True, help_text='"Заголовок" не отображается на сайте.', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to=content.models.employees.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='team', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='main_specialities',
            field=models.TextField(verbose_name='Специальности на общей странице'),
        ),
        migrations.AlterField(
            model_name='fundraisingphoto',
            name='image',
            field=models.ImageField(upload_to=content.models.targeted_fundraisings.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=content.models.news.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='file',
            field=models.ImageField(upload_to='gratitudes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Файл благодарности'),
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='title',
            field=models.CharField(blank=True, help_text='"Заголовок" не отображается на сайте.', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='show_on_main',
            field=models.BooleanField(default=True, verbose_name='Отображение на странице Новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Логотип партнера'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.ImageField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to=content.models.report.upload_file, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл отчета'),
        ),
    ]
