# Generated by Django 4.2 on 2025-06-19 09:05

import django.core.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_galleryimage_options_alter_gratitude_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('profession', models.CharField(max_length=200, verbose_name='Профессия')),
                ('photo', models.ImageField(upload_to='vacancies/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('salary', models.CharField(max_length=200, verbose_name='Зарплата')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткий текст')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='График')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('redirect_type', models.CharField(choices=[('detail', 'На страницу "Вакансии_подробная"'), ('form', 'На форму "Форма регистрации и отклика"')], default='detail', max_length=10, verbose_name='Тип перехода')),
                ('additional_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Дополнительное описание')),
                ('detailed_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание вакансии')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на внешнюю платформу')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
