# Generated by Django 4.2 on 2025-06-17 15:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_galleryimage_options_alter_gratitude_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('short_text', models.TextField(verbose_name='Краткий текст')),
                ('service_price', models.CharField(help_text='внести текст и/или цифры', max_length=255, verbose_name='цена услуги')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='место')),
                ('course_format', models.CharField(choices=[('online', 'онлайн'), ('offline', 'офлайн')], max_length=7, verbose_name='формат курса')),
            ],
            options={
                'verbose_name': 'Консультация и обучение',
                'verbose_name_plural': 'Консультации и обучения',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coaching/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='content.coaching', verbose_name='Консультации и обучение')),
            ],
            options={
                'verbose_name': 'Фотография Консультаций и обучения',
                'verbose_name_plural': 'Фотографии Консультаций и обучения',
            },
        ),
        migrations.CreateModel(
            name='ButtonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(choices=[('aba_therapy', 'Узнать больше о АБА-терапия'), ('contacts', 'Позвонить'), ('news', 'Узнать больше о новости')], max_length=11, verbose_name='Кнопка')),
                ('link_button', models.URLField(blank=True, help_text='Ссылка вводится только для новости', null=True, verbose_name='Ссылка на страницу новости')),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_link', to='content.coaching', verbose_name='Консультации и обучение')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
            },
        ),
    ]
