# Generated by Django 4.2 on 2025-06-26 18:19

import content.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAndInternships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('add_info', models.CharField(blank=True, max_length=25, verbose_name='Дополнительная информация')),
                ('info', django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='Дополнительная информация')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата')),
                ('format_study', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('hybrid', 'Гибридный')], default='online', max_length=7, verbose_name='Формат обучения')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='Краткое описание')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='Текстовый блок')),
                ('text_on_button', models.CharField(blank=True, max_length=255, verbose_name='Текст на кнопке')),
                ('action_on_button', models.CharField(choices=[('deteil', 'Подробная страница'), ('registration', 'Форма регистрации и отклика'), ('url', 'Ссылка на новость')], default='deteil', max_length=12, verbose_name='Действие на кнопке')),
                ('linked_news', models.URLField(blank=True, null=True, verbose_name='Произвольная ссылка')),
            ],
            options={
                'verbose_name': 'Обучение и стажировка',
                'verbose_name_plural': 'Обучение и стажировки',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TAIPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('on_main', models.BooleanField(default=False, verbose_name='На главной странице')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='content.trainingandinternships', verbose_name='Обучение и стажировка')),
            ],
            options={
                'verbose_name': 'Фотография карточки обучения и стажировок',
                'verbose_name_plural': 'Фотографии карточек обучения и стажировок',
            },
        ),
    ]
