# Generated by Django 4.2 on 2025-06-27 14:11

import content.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_coaching_coachingphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('detailed_page', models.CharField(choices=[('detailed', 'База знаний подробная'), ('link', 'Ссылка на существующую страницу')], max_length=8, verbose_name='Выбор подробной страницы')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на существующую страницу')),
                ('video', models.FileField(blank=True, null=True, upload_to='article/', validators=[django.core.validators.FileExtensionValidator(['avi', 'mp4'])], verbose_name='Видео файл')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Статья Базы знаний',
                'verbose_name_plural': 'Статьи Базы знаний',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ChapterKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Раздел Базы знаний',
                'verbose_name_plural': 'Разделы Базы знаний',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ArticleTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='текст статьи')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='article/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_block', to='content.article', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'Текстовый блок статьи Базы знаний',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='article/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фотография')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.article', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'Галерея фото статьи Базы знаний',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='content.chapterknowledgebase', verbose_name='Раздел Базы знаний'),
        ),
    ]
