# Generated by Django 4.2 on 2025-06-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_coaching_coachingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='URL-слаг'),
            preserve_default=False,
        ),
    ]
