# Generated by Django 4.2 on 2025-06-26 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_direction_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='supervisors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Фото')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('directions', models.ManyToManyField(to='content.direction', verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'Супервизор',
                'verbose_name_plural': 'Супервизоры',
                'ordering': ['order'],
            },
        ),
    ]
