# Generated by Django 4.2 on 2025-07-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_article_chapterknowledgebase_articletextblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterUsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Полезные ссылки - разделы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ArticleUsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_useful_links', to='content.chapterusefullinks', verbose_name='Раздел Полезные ссылки')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Полезные ссылки - статьи',
                'ordering': ('title',),
            },
        ),
    ]
