# Generated by Django 4.2 on 2025-07-02 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_chapterusefullinks_articleusefullinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('author', models.CharField(max_length=255, verbose_name='Автор(ы)')),
                ('publication_year', models.PositiveSmallIntegerField(default=2000, verbose_name='Год издания')),
                ('cover', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Обложка')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('button_type', models.CharField(choices=[('file', 'Прикрепить файл'), ('link', 'Прикрепить ссылку')], default='file', max_length=4, verbose_name='Тип кнопки')),
                ('file', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'epub', 'mobi', 'azw', 'azw3', 'fb2', 'djvu', 'txt', 'rtf', 'doc', 'docx'])], verbose_name='Файл литературы')),
                ('literature_url', models.URLField(blank=True, verbose_name='Ссылка на литературу')),
            ],
            options={
                'verbose_name': 'Литература',
                'verbose_name_plural': 'Литература',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
