# Generated by Django 4.2 on 2025-08-08 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_trainingandinternships_trainingandinternshipsphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.chapterknowledgebase', verbose_name='Раздел Базы знаний'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='content.article', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articletextblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='content.article', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='coaching',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='coachingphoto',
            name='coaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.coaching', verbose_name='Консультации и обучение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='directions',
            field=models.ManyToManyField(related_name='news', related_query_name='news', to='content.direction', verbose_name='Направление деятельности'),
        ),
        migrations.AlterField(
            model_name='news',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', related_query_name='news', to='content.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.programsprojects', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_financing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.partner', verbose_name='Источник софинансирования - Партнёр'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='content.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='directions',
            field=models.ManyToManyField(related_name='supervisors', to='content.direction', verbose_name='Направление деятельности'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['order'], name='content_cha_order_2c17ad_idx'),
        ),
        migrations.AddIndex(
            model_name='coaching',
            index=models.Index(fields=['order'], name='content_coa_order_2cd9be_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['order'], name='content_emp_order_a4ba32_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['news', 'order'], name='content_gal_news_id_b5d8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='gratitude',
            index=models.Index(fields=['order'], name='content_gra_order_9d4e18_idx'),
        ),
        migrations.AddIndex(
            model_name='literature',
            index=models.Index(fields=['order'], name='content_lit_order_80f923_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['order'], name='content_par_order_fdc736_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['order'], name='content_pro_order_b89520_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['chapter', 'order'], name='content_rep_chapter_4cac7f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order'], name='content_rev_order_c737ac_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisor',
            index=models.Index(fields=['order'], name='content_sup_order_837bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingandinternshipsphoto',
            index=models.Index(fields=['order'], name='content_tra_order_6ef70d_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['order'], name='content_vac_order_23e7d8_idx'),
        ),
    ]
