# Generated by Django 4.2 on 2025-08-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_article_chapter_alter_articlegallery_article_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['show_on_main', '-date'], name='news_main_date_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['project', '-date'], name='news_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-date', 'id'], name='news_date_id_idx'),
        ),
    ]
