# Generated by Django 4.2 on 2025-08-18 11:56

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_news_news_main_date_idx_news_news_project_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusvideo',
            name='title',
            field=models.CharField(blank=True, default='', help_text='"Заголовок" не отображается на сайте.', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaching',
            name='link_button',
            field=models.URLField(blank=True, default='', help_text='Ссылка вводится только для новости', verbose_name='Ссылка на страницу новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coaching',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='место'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='title',
            field=models.CharField(blank=True, default='', help_text='"Заголовок" не отображается на сайте.', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='detail_page_link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на подробную страницу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Основной текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingandinternships',
            name='text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Текстовый блок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Дополнительное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='detailed_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Описание вакансии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='external_link',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на внешнюю платформу'),
            preserve_default=False,
        ),
    ]
