# Generated by Django 4.2 on 2025-08-20 11:42

import content.models.employees
import content.models.knowledge_base
import content.models.news
import content.models.targeted_fundraisings
import content.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_aboutusvideo_title_alter_coaching_link_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraisingtextblock',
            name='fundraising',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['employee__name', 'type__name', 'file'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Дипломы и сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='fundraisingphoto',
            options={'ordering': ['order'], 'verbose_name': 'Фотография сбора', 'verbose_name_plural': 'Фотографии сборов'},
        ),
        migrations.AlterModelOptions(
            name='targetedfundraising',
            options={'ordering': ['order'], 'verbose_name': 'Адресный сбор', 'verbose_name_plural': 'Адресные сборы'},
        ),
        migrations.RemoveConstraint(
            model_name='fundraisingphoto',
            name='unique_photo_position',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fundraisingphoto',
            name='position',
        ),
        migrations.RemoveField(
            model_name='fundraisingphoto',
            name='title',
        ),
        migrations.AddField(
            model_name='fundraisingphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetedfundraising',
            name='bottom_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 290', verbose_name='Нижний текстовый блок'),
        ),
        migrations.AddField(
            model_name='targetedfundraising',
            name='center_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', validators=[content.validators.validate_not_empty_html], verbose_name='Центральный текстовый блок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetedfundraising',
            name='top_text_block',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Рекомендованное количество символов - 370', verbose_name='Верхний текстовый блок'),
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='foto',
            field=models.ImageField(upload_to=content.models.knowledge_base.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='articletextblock',
            name='foto',
            field=models.ImageField(blank=True, upload_to=content.models.knowledge_base.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='coachingphoto',
            name='image',
            field=models.ImageField(upload_to='coaching/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(upload_to=content.models.employees.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='content.typedocument', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category_on_main',
            field=models.BooleanField(default=False, verbose_name='Отображать категории документов на главной странице'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='team', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='максимальное количество символов - 19', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialities',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='максимальное количество символов - 45', validators=[content.validators.validate_not_empty_html], verbose_name='Специальности'),
        ),
        migrations.AlterField(
            model_name='fundraisingphoto',
            name='image',
            field=models.ImageField(upload_to=content.models.targeted_fundraisings.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=content.models.news.upload_file, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='file',
            field=models.ImageField(upload_to='gratitudes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Файл благодарности'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Логотип партнера'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=models.ImageField(upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='image',
            field=models.ImageField(upload_to='supervisors/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='targetedfundraising',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='trainingandinternshipsphoto',
            name='image',
            field=models.ImageField(upload_to='training/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='photo',
            field=models.ImageField(upload_to='vacancies/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'jfif'])], verbose_name='Фотография'),
        ),
        migrations.AddIndex(
            model_name='fundraisingphoto',
            index=models.Index(fields=['fundraising', 'order'], name='content_fun_fundrai_13ceb6_idx'),
        ),
        migrations.DeleteModel(
            name='FundraisingTextBlock',
        ),
    ]
