# Generated by Django 4.2 on 2025-08-20 11:57

import content.validators
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_fundraisingtextblock_fundraising_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialities',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[content.validators.validate_not_empty_html], verbose_name='Специальности'),
        ),
    ]
