# Generated by Django 4.2 on 2025-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_employee_name_alter_employee_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsprojects',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
