name: Deploy Django App

on:
  push:
    branches: [ dev ]

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/rassvet_app/rassvet_backend
          git pull origin dev
          sudo docker-compose -f docker-compose.dev.yml down
          sudo docker-compose -f docker-compose.dev.yml up -d --build
          sudo docker system prune -af
